services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      AWESOMETAX_URL: http://awesometax:8081
      DB_HOST: db
      SMTP_HOST: maildev
    depends_on:
      - db
      - awesometax
      - maildev
      - rabbitmq
  awesometax:
    build: ../awesometax
    ports:
      - "8081:8081"
  db:
    build: ../db
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    ports:
      - "8082:8080"
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
  rabbitmq:
    build: ../rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
